/* AUTOGENERATED FILE. DO NOT EDIT. */

/*=======Test Runner Used To Run Each Test Below=====*/
#define RUN_TEST(TestFunc, TestLineNum) \
{ \
  Unity.CurrentTestName = #TestFunc; \
  Unity.CurrentTestLineNumber = TestLineNum; \
  Unity.NumberOfTests++; \
  if (TEST_PROTECT()) \
  { \
      setUp(); \
      TestFunc(); \
  } \
  if (TEST_PROTECT()) \
  { \
    tearDown(); \
  } \
  UnityConcludeTest(); \
}

/*=======Automagically Detected Files To Include=====*/
#include "unity.h"
#include <setjmp.h>
#include <stdio.h>
#include <stdlib.h>
#include "MemPool_Test.h"
#include "MemPool.h"

/*=======External Functions This Runner Calls=====*/
extern void setUp(void);
extern void tearDown(void);

/*=======Test Reset Option=====*/
void resetTest(void);

void resetTest(void)
{
  tearDown();
  setUp();
}


/*=======MAIN=====*/
int main(void)
{
  UnityBegin("test/MemPool.c");

  uint8 * mempool = aligned_alloc(MEMPOOL_BLOCK_SIZE, MEMPOOL_SIZE);
  mempool_start = mempool;
  printf("Address of mempool: %p\n", (void*)MEMPOOL_STARTADDR);
  printf("Length of mempool: %p\n", (void*)(MEMPOOL_BLOCK_SIZE*MEMPOOL_MAX_NUM_BLOCKS));

  /* Tests for Create() */
  RUN_TEST(test_MemPool_Create_ReturnsOK, 54);
  RUN_TEST(test_MemPool_Create_ReturnsNotOk_UnalignedStartAddress, 55);
  RUN_TEST(test_MemPool_Create_ReturnsNotOk_UnalignedSize, 56);
  RUN_TEST(test_MemPool_Create_ReturnsNotOk_ZeroSize, 57);
  RUN_TEST(test_MemPool_Create_Persists_AlignedSize, 58);
  RUN_TEST(test_MemPool_Create_Persists_AlignedAddress, 59);
  RUN_TEST(test_MemPool_Create_Persists_BlockCount, 60);
  RUN_TEST(test_MemPool_Create_FreeBlockCountIsCorrect, 61);
  RUN_TEST(test_MemPool_Create_BlockArrayIsAllFree, 62);

  RUN_TEST(test_MemPool_CheckRangeContained_OK, 64);
  RUN_TEST(test_MemPool_CheckRangeContained_OK_FullRange, 65);
  RUN_TEST(test_MemPool_CheckRangeContained_StartInLengthOut_NOTOK, 66);
  RUN_TEST(test_MemPool_CheckRangeContained_StartOutLengthIn_NOTOK, 67);
  RUN_TEST(test_MemPool_CheckRangeContained_StartOutLengthOut_NOTOK, 68);
  RUN_TEST(test_MemPool_CheckRangeContained_StartInLengthHuge_OVERFLOW_NOTOK, 69);

  RUN_TEST(test_MemPool_Alloc_ReturnsPointer, 71);
  RUN_TEST(test_MemPool_Alloc_SizeZero_ReturnsNULL, 72);
  RUN_TEST(test_MemPool_Alloc_SizeTooBig_ReturnsNULL, 73);
  RUN_TEST(test_MemPool_Alloc_AllocOneBlock, 74);
  RUN_TEST(test_MemPool_Alloc_AllocTwoBlocks_TwoDifferentIdentifiers_TwoRequest, 75);
  RUN_TEST(test_MemPool_Alloc_AllocTwoBlocks_OneRequest, 76);
  RUN_TEST(test_MemPool_Alloc_AllocThreeBlocks, 77);
  RUN_TEST(test_MemPool_Alloc_AllocAllBlocks_ReturnsPointer, 78);
  RUN_TEST(test_MemPool_Alloc_AllocTooManyBlocks_ReturnsNull, 79);
  RUN_TEST(test_MemPool_Alloc_AllocAllBlocks_AllPointersInMemPool, 80);
  RUN_TEST(test_MemPool_Alloc_AllocAllBlocks_AllPointersDifferent, 81);

  RUN_TEST(test_MemPool_Free_ReturnsOK, 81);
  RUN_TEST(test_MemPool_Free_PointerNotInMemPool_ReurnsNOTOK, 81);
  RUN_TEST(test_MemPool_Free_PointerInMempoolButNotCorrectModule_ReturnsNOTOK, 81);
  RUN_TEST(test_MemPool_Free_FreesCorrectSpace_AllocOneBlockAndFreeOneBlock_IsFree, 81);
  RUN_TEST(test_MemPool_Free_FreesCorrectSpace_AllocTwoBlocksAndFreeOneBlock_IsFreeAndAlloc, 81);
  RUN_TEST(test_MemPool_Free_FreesCorrectSpace_AllocAllAsOneAndFreeAll_AllIsFree, 81);
  RUN_TEST(test_MemPool_Free_NumBlocksEqualsNumFreeBlocks, 89);
  RUN_TEST(test_MemPool_Free_1BlockFreeAfterAllUsedAnd1Freed, 90);

  /* Auxiliary tests */
  RUN_TEST(test_MemPool_Aux_CanaryTest, 93);
  RUN_TEST(test_MemPool_Aux_AllocAllFreeHalfAllocOne, 94);

  return (UnityEnd());
}
